services:
  mysql-db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: departmentservice_db
    ports:
      - "8081:8081"
    command: --default-authentication-plugin=mysql_native_password
