services:
  mysql-db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organizationservice_db
    ports:
      - "8082:8082"
    command: --default-authentication-plugin=mysql_native_password
